---
title: "GAL_TAN and salience"
output: html_document
date: '2022-05-06'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preparations

## Packages

```{r}
library(rio)
library(ggplot2)
```

## Data

```{r}

d<-import("../../data/processed/CHES_2014.vote.keys.combined.xlsx")

m.galtan<-mean(d$galtan,na.rm=T)
sd.galtan<-sd(d$galtan,na.rm=T)

m.galtan_salience<-mean(d$galtan_salience,na.rm=T)
sd.galtan_salience<-sd(d$galtan_salience,na.rm=T)

hist(d$galtan_salience)

m.lrecon<-mean(d$lrecon,na.rm=T)
sd.lrecon<-sd(d$lrecon,na.rm=T)

m.lrecon_salience<-mean(d$lrecon_salience,na.rm=T)
sd.lrecon_salience<-sd(d$lrecon_salience,na.rm=T)

hist(d$lrecon_salience)

m.lrecon_salience
sd.lrecon_salience

d[d$lrecon_salience>m.lrecon_salience+sd.lrecon_salience,"pt.name"]

```

## Describe parties

### Correlation

```{r}
cor.test(d$galtan,d$galtan_salience)
cor.test(d$lrecon,d$lrecon_salience)
```

### Scatterplot

```{r}
names(d)
ggplot(d,aes(x=galtan_salience,y=galtan))+
  geom_point()+
  geom_label(aes(label=ifelse((galtan>m.galtan+sd.galtan |
                                galtan<m.galtan-sd.galtan) &
                                (galtan_salience>m.galtan_salience+sd.galtan_salience |
                                galtan_salience<m.galtan_salience-sd.galtan_salience)
                                , pt.name,"")),size=2)+
  xlim(c(0,10))+
  ylim(c(0,10))


ggplot(d,aes(x=lrecon_salience,y=lrecon))+
  geom_point()+
  geom_label(aes(label=ifelse((lrecon>m.lrecon+sd.lrecon |
                                lrecon<m.lrecon-sd.lrecon) &
                                (lrecon_salience>m.lrecon_salience+sd.lrecon_salience |
                                lrecon_salience<m.lrecon_salience-sd.lrecon_salience)
                                , pt.name,"")),size=2)
  xlim(c(0,10))+
  ylim(c(0,10))
```

### Frequencies

```{r}
table(d$galtan>(m.galtan+sd.galtan))
table(d$galtan<(m.galtan-sd.galtan))

table(d$galtan_salience>(m.galtan_salience+sd.galtan_salience))
table(d$galtan_salience<(m.galtan_salience-sd.galtan_salience))

# high galtan, low salience
table(d$galtan>(m.galtan+sd.galtan) &
        d$galtan_salience<(m.galtan_salience-sd.galtan_salience))

```